# Generated by Django 5.1.5 on 2025-03-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0002_notification_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='follow',
        ),
    ]
