# Generated by Django 5.1.5 on 2025-01-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
