# Generated by Django 5.1.5 on 2025-02-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_comment_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
